---
- predicate: :valuables_present?
  method: :generate_valuable_possessions_entity
  entity_name: VALUABLE_POSSESSION
  instance_label: the valuable possession1
  yaml_section: :valuable_possessions

- predicate: :bank_accounts_present?
  method: :generate_bank_accounts_entity
  entity_name: BANKACC
  yaml_section: :bank_acct

- method: :generate_means_proceeding_entity
  entity_name: PROCEEDING
  yaml_section: :proceeding_means

- method: :generate_opponent_other_parties_means_entity
  entity_name: OPPONENT_OTHER_PARTIES
  yaml_section: :opponent_other_parties_means

- method: :generate_entity
  entity_name: global
  instance_label: "#submission_case_ccms_reference"
  yaml_section: :global_means
