---
http_interactions:
- request:
    method: get
    uri: https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk/client_involvement_types
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v2.7.12
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 14 Dec 2023 08:37:17 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '277'
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"8bf337339345d42d16a9e6062fb65ccf"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a846ed918c2363af33eb75aa8a4e3313
      X-Runtime:
      - '0.003911'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '[{"ccms_code":"A","description":"Applicant/claimant/petitioner"},{"ccms_code":"D","description":"Defendant/respondent"},{"ccms_code":"W","description":"Subject
        of proceedings (child)"},{"ccms_code":"I","description":"Intervenor"},{"ccms_code":"Z","description":"Joined
        party"}]'
  recorded_at: Thu, 14 Dec 2023 08:37:17 GMT
recorded_with: VCR 6.2.0
