---
http_interactions:
- request:
    method: post
    uri: https://legal-framework-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/merits_tasks
    body:
      encoding: UTF-8
      string: '{"request_id":"a8ecca4e-be6a-438a-91d1-664088fb049e","proceeding_types":["DA005","DA001","DA003"]}'
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.3.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 16 Apr 2021 15:52:19 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept
      Etag:
      - W/"1bf668115aa40e6834a15836fe17fe81"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - dd29972c555d84d6b14dd3418586e891
      X-Runtime:
      - '0.068696'
      Strict-Transport-Security:
      - max-age=15724800; includeSubDomains
    body:
      encoding: UTF-8
      string: '{"request_id":"a8ecca4e-be6a-438a-91d1-664088fb049e","success":true,"application":{"tasks":{"latest_incident_details":[],"opponent_details":[],"statement_of_case":[]}},"proceeding_types":[{"ccms_code":"DA005","tasks":{"chances_of_success":[]}},{"ccms_code":"DA001","tasks":{"chances_of_success":[]}},{"ccms_code":"DA003","tasks":{"chances_of_success":[]}}]}'
  recorded_at: Fri, 16 Apr 2021 15:52:19 GMT
recorded_with: VCR 6.0.0
